### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by hurzl** [citygml4j/citygml4j#1]
Any Idea? Thanks

```
      [xjc] Checking timestamp of ..../citygml4j/resources/jaxb/schemas/GML/3.1.1/xlink/xlink.xsd
      [xjc] Checking timestamp of ..../citygml4j/resources/jaxb/schemas/GML/3.1.1/xml/xml.xsd
      [xjc] Checking timestamp of ..../citygml4j/resources/jaxb/schemas/xAL/2.0/xAL.xsd
      [xjc] the last modified time of the inputs is  1429258950000
      [xjc] the last modified time of the outputs is -9223372036854775808
      [xjc] Compiling file:..../citygml4j/resources/jaxb/schemas/CityGML/citygml4j_profile.xsd
      [xjc] removing old output files
      [xjc] [ERROR] schema_reference: Schemadokument "appearance.xsd" konnte nicht gelesen werden, weil der "file"-Zugriff wegen der von der Eigenschaft accessExternalSchema festgelegten Einschränkung nicht zulässig ist. 
      [xjc]   Zeile 22 von file:..../citygml4j/resources/jaxb/schemas/CityGML/citygml4j_profile.xsd
      [xjc] 
      [xjc] failure in the XJC task. Use the Ant -verbose switch for more details

BUILD FAILED
..../citygml4j/build.xml:60: unable to parse the schema. Error messages should have been provided
        at com.sun.tools.xjc.XJC2Task._doXJC(XJC2Task.java:520)
        at com.sun.tools.xjc.XJC2Task.doXJC(XJC2Task.java:457)
        at com.sun.tools.xjc.XJC2Task.execute(XJC2Task.java:380)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 1 second
```

in english:
```
      [xjc] [ERROR] schema_reference: Failed to read schema document 'appearance.xsd', because 'file' access is not allowed due to restriction set by the accessExternalSchema property. 

```

**Comment by clausnagel** [comment]
The XJC taskdef in ```build.xml``` produces this error when accessing the ```<xs:import>s``` in ```resources/jaxb/schemas/CityGML/citygml4j_profile.xsd```. This is due to [XML security properties](http://docs.oracle.com/javase/tutorial/jaxp/properties/properties.html) in JAXP 1.5 introduced with Java SE 7u40 and 8 releases.

The mandatory JAXB classes mapping the CityGML XML schemas were therefore precompiled and added to ```src-gen``` in the master branch (see 65b4aaae5c9142633a22b5b998cf4277b3c3d77e). You should not need to compile them anew when building the library. Have you pulled the latest changes from master?

To get around this issue, simply include the ```javax.xml.accessExternalSchema=file``` property in ```ANT_OPTS``` before running the Ant build (tested with Ant 1.9.0 on Windows 7).

    % set ANT_OPTS="-Djavax.xml.accessExternalSchema=file"
    % ant dist

Alternatively, you might want to specify this property in ```${java.home}/lib/jaxp.properties``` to define the behavior for all applications using the Java Runtime.

**Comment by hurzl** [comment]
Thanks, that solves it. I found the binaries in the meatine ... ;)

And yes I had the latest source.
